project:
  type: website

website:
  title: "Police Shootings"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - background.qmd
      - data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

